services:
  dice:
    image: shiaworkshop/dice:latest
    container_name: dice-main
    stdin_open: true
    tty: true
    working_dir: /app/Dice
    volumes:
      - "./Dice:/app/Dice"
      - "./napcat/config:/app/napcat/config"
    environment:
      - ACCOUNT=${ACCOUNT}
    networks:
      - dice
    depends_on:
      - napcat

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    hostname: ShiaDiceFlats
    ports:
      - "6099:6099"
    volumes:
      - "./napcat/config:/app/napcat/config"
      - "./napcat/QQ_DATA:/app/.config/QQ"
      - "./Dice:/app/Dice"
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
      - ACCOUNT=${ACCOUNT}
    networks:
      - dice
    mac_address: "02:42:8f:51:b2:a1"

networks:
  dice:
    driver: bridge