name: Docker Build and Push

on:
  workflow_dispatch:

env:
  DOCKERHUB_REPO: shiaworkshop/dice
  DLL_SEARCH_PATH: ./Dice/Diceki
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 读取版本号文件
        id: read_version
        run: |
          if [ ! -f "last_release.txt" ]; then
            echo "::error::last_release.txt 文件不存在"
            exit 1
          fi
          
          VERSION_TAG=$(cat last_release.txt | tr -d '\n\r' | grep -Eo '[0-9]+')
          if [ -z "$VERSION_TAG" ]; then
            echo "::error::last_release.txt 中未找到有效版本号"
            exit 1
          fi
          
          echo "版本号: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:  ${{ env.VERSION_TAG }}