name: Docker Build and Push

on:
  workflow_dispatch:

env:
  DOCKERHUB_REPO: shiaworkshop/dice
  DLL_SEARCH_PATH: ./Dice/Diceki
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 查找最大版本号
        id: find_version
        run: |
          echo "当前工作目录: $(pwd)"
          echo "正在搜索目录: ${{ env.DLL_SEARCH_PATH }}"
          
          # 调试：显示找到的文件列表
          find "${{ env.DLL_SEARCH_PATH }}" -name "*.dll" | while read -r file; do
            echo "找到文件: $file"
          done
          
          max_version=0
          for file in $(find "${{ env.DLL_SEARCH_PATH }}" -name "*.dll"); do
            echo "正在处理文件: $file"
            
            # 使用兼容性更强的正则表达式
            version=$(basename "$file" | sed -nE 's/.*$(.*)$/\1/p' | grep -E '^[0-9]+$' || echo "0")
            echo "提取到的版本号: $version"
            
            # 数值比较
            if [ "$version" -gt "$max_version" ]; then
              max_version=$version
              echo "更新最大版本号为: $max_version"
            fi
          done
          
          if [ "$max_version" -eq 0 ]; then
            echo "::error::未找到有效版本号 (示例期待文件名格式：filename(638).dll)"
            echo "找到的文件列表："
            find "${{ env.DLL_SEARCH_PATH }}" -name "*.dll" -ls
            exit 1
          fi
          
          echo "最终确定版本号: $max_version"
          echo "VERSION_TAG=$max_version" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:  ${{ env.VERSION_TAG }}